# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.3.1"
  python_check_max: "3.14"

package:
  name: toml-fmt-common
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/t/toml-fmt-common/toml_fmt_common-${{ version }}.tar.gz
    sha256: da19c5a485e9f3f1f154a54e05c7b4aadd6147478286d7547e91ba54e4f755fc
  - url: https://raw.githubusercontent.com/tox-dev/toml-fmt/refs/heads/main/LICENSE.txt
    sha256: 90e25e1faf2a4aaea8d95ee8e7f5738b052a1acc0c9c58068101f931a86bd588

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build >=0.7.22,<0.8
  run:
    - python >=${{ python_min }}
    - tomli >=2.4

tests:
  - python:
      imports: toml_fmt_common
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  # TODO: restore tests when upstream provides tests in sdist or at least predictable tags
  # - files:
  #     source:
  #       - tests/
  #   requirements:
  #     run:
  #       - coverage
  #       - pytest
  #       - pytest-mock
  #       - python ${{ python_min }}.*
  #   script:
  #     - if: unix
  #       then:
  #         - coverage run --source=toml_fmt_common -m pytest -vv --tb=long --color=yes
  #         - coverage report --show-missing --skip-covered --fail-under=95
  #       else:
  #         - pytest -vv --tb=long --color=yes -k "not (is_folder or no_read)"

about:
  summary: Common logic to the TOML formatter.
  license: MIT
  license_file: LICENSE.txt
  homepage: https://pypi.org/project/toml-fmt-common
  repository: https://github.com/tox-dev/toml-fmt/tree/main/toml-fmt-common

extra:
  recipe-maintainers:
    - bollwyvl
